routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});

/*
 * Subscribers Routes
 */
Route::resource('subscribers', 'SubscriberController');

/*
 * Aliases Routes
 */
Route::resource('aliases', 'AliasController');

/*
 * Reviews Routes
 */
Route::resource('reviews', 'ReviewController');

/*
 * Hoteliers Routes
 */
Route::resource('hoteliers', 'HotelierController');

/*
 * Hotels Routes
 */
Route::resource('hotels', 'HotelController');

/*
 * Photos Routes
 */
Route::resource('photos', 'PhotoController');

/*
 * Favourites Routes
 */
Route::resource('favourites', 'FavouriteController');

/*
 * SimilarHotels Routes
 */
Route::resource('similar_hotels', 'SimilarHotelController');

/*
 * HotelReviewRatings Routes
 */
Route::resource('hotel_review_ratings', 'HotelReviewRatingController');

/*
 * AnswerHotelQuestions Routes
 */
Route::resource('answer_hotel_questions', 'AnswerHotelQuestionController');

/*
 * SummaryStayTypes Routes
 */
Route::resource('summary_stay_types', 'SummaryStayTypeController');

/*
 * HotelServices Routes
 */
Route::resource('hotel_services', 'HotelServiceController');

/*
 * ReviewUsefulnesses Routes
 */
Route::resource('review_usefulnesses', 'ReviewUsefulnessController');

/*
 * HotelCategories Routes
 */
Route::resource('hotel_categories', 'HotelCategoryController');

/*
 * PriceRanges Routes
 */
Route::resource('price_ranges', 'PriceRangeController');

/*
 * Countries Routes
 */
Route::resource('countries', 'CountryController');

/*
 * VisitDates Routes
 */
Route::resource('visit_dates', 'VisitDateController');

/*
 * HotelQuestions Routes
 */
Route::resource('hotel_questions', 'HotelQuestionController');

/*
 * Services Routes
 */
Route::resource('services', 'ServiceController');

/*
 * HotelReviewTypes Routes
 */
Route::resource('hotel_review_types', 'HotelReviewTypeController');

/*
 * VisitTypes Routes
 */
Route::resource('visit_types', 'VisitTypeController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


/**
 * Multi-Authentication Routes
 */
Route::get('/login/subscriber', 'Auth\LoginController@showSubscriberLoginForm')->name('login_subscriber');
Route::get('/login/hotelier', 'Auth\LoginController@showHotelierLoginForm')->name('login_hotelier');
Route::get('/register/subscriber', 'Auth\RegisterController@showSubscriberRegisterForm')->name('register_subscriber');
Route::get('/register/hotelier', 'Auth\RegisterController@showHotelierRegisterForm')->name('register_hotelier');

Route::post('/login/subscriber', 'Auth\LoginController@subscriberLogin');
Route::post('/login/hotelier', 'Auth\LoginController@hotelierLogin');
Route::post('/register/subscriber', 'Auth\RegisterController@createSubscriber');
Route::post('/register/hotelier', 'Auth\RegisterController@createHotelier');

Route::view('/home', 'home')->middleware('auth');
Route::view('/dashboard', 'dashboard');

app/PriceRange.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class PriceRange extends Model
{
    protected $fillable = ['name', 'description', 'creator_id'];

    public function getNameLinkAttribute()
    {
        $title = __('app.show_detail_title', [
            'name' => $this->name, 'type' => __('price_range.price_range'),
        ]);
        $link = '<a href="'.route('price_ranges.show', $this).'"';
        $link .= ' title="'.$title.'">';
        $link .= $this->name;
        $link .= '</a>';

        return $link;
    }

    public function creator()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the Hotels for the price range.
     */
    public function hotels()
    {
        return $this->hasMany(Hotel::class);
    }
}

app/Http/Controllers/PriceRangeController.php
<?php

namespace App\Http\Controllers;

use App\PriceRange;
use Illuminate\Http\Request;

class PriceRangeController extends Controller
{
    /**
     * Display a listing of the priceRange.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $priceRangeQuery = PriceRange::query();
        $priceRangeQuery->where('name', 'like', '%'.request('q').'%');
        $priceRanges = $priceRangeQuery->paginate(25);

        return view('price_ranges.index', compact('priceRanges'));
    }

    /**
     * Show the form for creating a new priceRange.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $this->authorize('create', new PriceRange);

        return view('price_ranges.create');
    }

    /**
     * Store a newly created priceRange in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->authorize('create', new PriceRange);

        $newPriceRange = $request->validate([
            'name'        => 'required|max:60',
            'description' => 'nullable|max:255',
        ]);
        $newPriceRange['creator_id'] = auth()->id();

        $priceRange = PriceRange::create($newPriceRange);

        return redirect()->route('price_ranges.show', $priceRange);
    }

    /**
     * Display the specified priceRange.
     *
     * @param  \App\PriceRange  $priceRange
     * @return \Illuminate\View\View
     */
    public function show(PriceRange $priceRange)
    {
        return view('price_ranges.show', compact('priceRange'));
    }

    /**
     * Show the form for editing the specified priceRange.
     *
     * @param  \App\PriceRange  $priceRange
     * @return \Illuminate\View\View
     */
    public function edit(PriceRange $priceRange)
    {
        $this->authorize('update', $priceRange);

        return view('price_ranges.edit', compact('priceRange'));
    }

    /**
     * Update the specified priceRange in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\PriceRange  $priceRange
     * @return \Illuminate\Routing\Redirector
     */
    public function update(Request $request, PriceRange $priceRange)
    {
        $this->authorize('update', $priceRange);

        $priceRangeData = $request->validate([
            'name'        => 'required|max:60',
            'description' => 'nullable|max:255',
        ]);
        $priceRange->update($priceRangeData);

        return redirect()->route('price_ranges.show', $priceRange);
    }

    /**
     * Remove the specified priceRange from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\PriceRange  $priceRange
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy(Request $request, PriceRange $priceRange)
    {
        $this->authorize('delete', $priceRange);

        $request->validate(['price_range_id' => 'required']);

        if ($request->get('price_range_id') == $priceRange->id && $priceRange->delete()) {
            return redirect()->route('price_ranges.index');
        }

        return back();
    }
}

resources/views/price_ranges/create.blade.php
@extends('layouts.app')

@section('title', __('price_range.create'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('price_range.create') }}</div>
            <form method="POST" action="{{ route('price_ranges.store') }}" accept-charset="UTF-8">
                {{ csrf_field() }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="form-label">{{ __('price_range.name') }} <span class="form-required">*</span></label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="description" class="form-label">{{ __('price_range.description') }}</label>
                        <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description') }}</textarea>
                        {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('price_range.create') }}" class="btn btn-success">
                    <a href="{{ route('price_ranges.index') }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/price_ranges/edit.blade.php
@extends('layouts.app')

@section('title', __('price_range.edit'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        @if (request('action') == 'delete' && $priceRange)
        @can('delete', $priceRange)
            <div class="card">
                <div class="card-header">{{ __('price_range.delete') }}</div>
                <div class="card-body">
                    <label class="form-label text-primary">{{ __('price_range.name') }}</label>
                    <p>{{ $priceRange->name }}</p>
                    <label class="form-label text-primary">{{ __('price_range.description') }}</label>
                    <p>{{ $priceRange->description }}</p>
                    {!! $errors->first('price_range_id', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                </div>
                <hr style="margin:0">
                <div class="card-body text-danger">{{ __('price_range.delete_confirm') }}</div>
                <div class="card-footer">
                    <form method="POST" action="{{ route('price_ranges.destroy', $priceRange) }}" accept-charset="UTF-8" onsubmit="return confirm(&quot;{{ __('app.delete_confirm') }}&quot;)" class="del-form float-right" style="display: inline;">
                        {{ csrf_field() }} {{ method_field('delete') }}
                        <input name="price_range_id" type="hidden" value="{{ $priceRange->id }}">
                        <button type="submit" class="btn btn-danger">{{ __('app.delete_confirm_button') }}</button>
                    </form>
                    <a href="{{ route('price_ranges.edit', $priceRange) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </div>
        @endcan
        @else
        <div class="card">
            <div class="card-header">{{ __('price_range.edit') }}</div>
            <form method="POST" action="{{ route('price_ranges.update', $priceRange) }}" accept-charset="UTF-8">
                {{ csrf_field() }} {{ method_field('patch') }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="form-label">{{ __('price_range.name') }} <span class="form-required">*</span></label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $priceRange->name) }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="description" class="form-label">{{ __('price_range.description') }}</label>
                        <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description', $priceRange->description) }}</textarea>
                        {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('price_range.update') }}" class="btn btn-success">
                    <a href="{{ route('price_ranges.show', $priceRange) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                    @can('delete', $priceRange)
                        <a href="{{ route('price_ranges.edit', [$priceRange, 'action' => 'delete']) }}" id="del-price_range-{{ $priceRange->id }}" class="btn btn-danger float-right">{{ __('app.delete') }}</a>
                    @endcan
                </div>
            </form>
        </div>
    </div>
</div>
@endif
@endsection

resources/views/price_ranges/index.blade.php
@extends('layouts.app')

@section('title', __('price_range.list'))

@section('content')
<div class="mb-3">
    <div class="float-right">
        @can('create', new App\PriceRange)
            <a href="{{ route('price_ranges.create') }}" class="btn btn-success">{{ __('price_range.create') }}</a>
        @endcan
    </div>
    <h1 class="page-title">{{ __('price_range.list') }} <small>{{ __('app.total') }} : {{ $priceRanges->total() }} {{ __('price_range.price_range') }}</small></h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <form method="GET" action="" accept-charset="UTF-8" class="form-inline">
                    <div class="form-group">
                        <label for="q" class="form-label">{{ __('price_range.search') }}</label>
                        <input placeholder="{{ __('price_range.search_text') }}" name="q" type="text" id="q" class="form-control mx-sm-2" value="{{ request('q') }}">
                    </div>
                    <input type="submit" value="{{ __('price_range.search') }}" class="btn btn-secondary">
                    <a href="{{ route('price_ranges.index') }}" class="btn btn-link">{{ __('app.reset') }}</a>
                </form>
            </div>
            <table class="table table-sm table-responsive-sm table-hover">
                <thead>
                    <tr>
                        <th class="text-center">{{ __('app.table_no') }}</th>
                        <th>{{ __('price_range.name') }}</th>
                        <th>{{ __('price_range.description') }}</th>
                        <th class="text-center">{{ __('app.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($priceRanges as $key => $priceRange)
                    <tr>
                        <td class="text-center">{{ $priceRanges->firstItem() + $key }}</td>
                        <td>{!! $priceRange->name_link !!}</td>
                        <td>{{ $priceRange->description }}</td>
                        <td class="text-center">
                            @can('view', $priceRange)
                                <a href="{{ route('price_ranges.show', $priceRange) }}" id="show-price_range-{{ $priceRange->id }}">{{ __('app.show') }}</a>
                            @endcan
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="card-body">{{ $priceRanges->appends(Request::except('page'))->render() }}</div>
        </div>
    </div>
</div>
@endsection

resources/views/price_ranges/show.blade.php
@extends('layouts.app')

@section('title', __('price_range.detail'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('price_range.detail') }}</div>
            <div class="card-body">
                <table class="table table-sm">
                    <tbody>
                        <tr><td>{{ __('price_range.name') }}</td><td>{{ $priceRange->name }}</td></tr>
                        <tr><td>{{ __('price_range.description') }}</td><td>{{ $priceRange->description }}</td></tr>
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                @can('update', $priceRange)
                    <a href="{{ route('price_ranges.edit', $priceRange) }}" id="edit-price_range-{{ $priceRange->id }}" class="btn btn-warning">{{ __('price_range.edit') }}</a>
                @endcan
                <a href="{{ route('price_ranges.index') }}" class="btn btn-link">{{ __('price_range.back_to_index') }}</a>
            </div>
        </div>
    </div>
</div>
@endsection