routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});

/*
 * Subscribers Routes
 */
Route::resource('subscribers', 'SubscriberController');

/*
 * Aliases Routes
 */
Route::resource('aliases', 'AliasController');

/*
 * Reviews Routes
 */
Route::resource('reviews', 'ReviewController');

/*
 * Hoteliers Routes
 */
Route::resource('hoteliers', 'HotelierController');

/*
 * Hotels Routes
 */
Route::resource('hotels', 'HotelController');

/*
 * Photos Routes
 */
Route::resource('photos', 'PhotoController');

/*
 * Favourites Routes
 */
Route::resource('favourites', 'FavouriteController');

/*
 * SimilarHotels Routes
 */
Route::resource('similar_hotels', 'SimilarHotelController');

/*
 * HotelReviewRatings Routes
 */
Route::resource('hotel_review_ratings', 'HotelReviewRatingController');

/*
 * AnswerHotelQuestions Routes
 */
Route::resource('answer_hotel_questions', 'AnswerHotelQuestionController');

/*
 * SummaryStayTypes Routes
 */
Route::resource('summary_stay_types', 'SummaryStayTypeController');

/*
 * HotelServices Routes
 */
Route::resource('hotel_services', 'HotelServiceController');

/*
 * ReviewUsefulnesses Routes
 */
Route::resource('review_usefulnesses', 'ReviewUsefulnessController');

/*
 * HotelCategories Routes
 */
Route::resource('hotel_categories', 'HotelCategoryController');

/*
 * PriceRanges Routes
 */
Route::resource('price_ranges', 'PriceRangeController');

/*
 * Countries Routes
 */
Route::resource('countries', 'CountryController');

/*
 * VisitDates Routes
 */
Route::resource('visit_dates', 'VisitDateController');

/*
 * HotelQuestions Routes
 */
Route::resource('hotel_questions', 'HotelQuestionController');

/*
 * Services Routes
 */
Route::resource('services', 'ServiceController');

/*
 * HotelReviewTypes Routes
 */
Route::resource('hotel_review_types', 'HotelReviewTypeController');

/*
 * VisitTypes Routes
 */
Route::resource('visit_types', 'VisitTypeController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


/**
 * Multi-Authentication Routes
 */
Route::get('/login/subscriber', 'Auth\LoginController@showSubscriberLoginForm')->name('login_subscriber');
Route::get('/login/hotelier', 'Auth\LoginController@showHotelierLoginForm')->name('login_hotelier');
Route::get('/register/subscriber', 'Auth\RegisterController@showSubscriberRegisterForm')->name('register_subscriber');
Route::get('/register/hotelier', 'Auth\RegisterController@showHotelierRegisterForm')->name('register_hotelier');

Route::post('/login/subscriber', 'Auth\LoginController@subscriberLogin');
Route::post('/login/hotelier', 'Auth\LoginController@hotelierLogin');
Route::post('/register/subscriber', 'Auth\RegisterController@createSubscriber');
Route::post('/register/hotelier', 'Auth\RegisterController@createHotelier');

Route::view('/home', 'home')->middleware('auth');
Route::view('/dashboard', 'dashboard');

app/Favourite.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Favourite extends Model
{
    protected $fillable = ['name', 'description', 'creator_id'];

    public function getNameLinkAttribute()
    {
        $title = __('app.show_detail_title', [
            'name' => $this->name, 'type' => __('favourite.favourite'),
        ]);
        $link = '<a href="'.route('favourites.show', $this).'"';
        $link .= ' title="'.$title.'">';
        $link .= $this->name;
        $link .= '</a>';

        return $link;
    }

    public function creator()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/FavouriteController.php
<?php

namespace App\Http\Controllers;

use App\Favourite;
use Illuminate\Http\Request;

class FavouriteController extends Controller
{
    /**
     * Display a listing of the favourite.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $favouriteQuery = Favourite::query();
        $favouriteQuery->where('name', 'like', '%'.request('q').'%');
        $favourites = $favouriteQuery->paginate(25);

        return view('favourites.index', compact('favourites'));
    }

    /**
     * Show the form for creating a new favourite.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $this->authorize('create', new Favourite);

        return view('favourites.create');
    }

    /**
     * Store a newly created favourite in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->authorize('create', new Favourite);

        $newFavourite = $request->validate([
            'name'        => 'required|max:60',
            'description' => 'nullable|max:255',
        ]);
        $newFavourite['creator_id'] = auth()->id();

        $favourite = Favourite::create($newFavourite);

        return redirect()->route('favourites.show', $favourite);
    }

    /**
     * Display the specified favourite.
     *
     * @param  \App\Favourite  $favourite
     * @return \Illuminate\View\View
     */
    public function show(Favourite $favourite)
    {
        return view('favourites.show', compact('favourite'));
    }

    /**
     * Show the form for editing the specified favourite.
     *
     * @param  \App\Favourite  $favourite
     * @return \Illuminate\View\View
     */
    public function edit(Favourite $favourite)
    {
        $this->authorize('update', $favourite);

        return view('favourites.edit', compact('favourite'));
    }

    /**
     * Update the specified favourite in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Favourite  $favourite
     * @return \Illuminate\Routing\Redirector
     */
    public function update(Request $request, Favourite $favourite)
    {
        $this->authorize('update', $favourite);

        $favouriteData = $request->validate([
            'name'        => 'required|max:60',
            'description' => 'nullable|max:255',
        ]);
        $favourite->update($favouriteData);

        return redirect()->route('favourites.show', $favourite);
    }

    /**
     * Remove the specified favourite from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Favourite  $favourite
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy(Request $request, Favourite $favourite)
    {
        $this->authorize('delete', $favourite);

        $request->validate(['favourite_id' => 'required']);

        if ($request->get('favourite_id') == $favourite->id && $favourite->delete()) {
            return redirect()->route('favourites.index');
        }

        return back();
    }
}

resources/views/favourites/create.blade.php
@extends('layouts.app')

@section('title', __('favourite.create'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('favourite.create') }}</div>
            <form method="POST" action="{{ route('favourites.store') }}" accept-charset="UTF-8">
                {{ csrf_field() }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="form-label">{{ __('favourite.name') }} <span class="form-required">*</span></label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="description" class="form-label">{{ __('favourite.description') }}</label>
                        <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description') }}</textarea>
                        {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('favourite.create') }}" class="btn btn-success">
                    <a href="{{ route('favourites.index') }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/favourites/edit.blade.php
@extends('layouts.app')

@section('title', __('favourite.edit'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        @if (request('action') == 'delete' && $favourite)
        @can('delete', $favourite)
            <div class="card">
                <div class="card-header">{{ __('favourite.delete') }}</div>
                <div class="card-body">
                    <label class="form-label text-primary">{{ __('favourite.name') }}</label>
                    <p>{{ $favourite->name }}</p>
                    <label class="form-label text-primary">{{ __('favourite.description') }}</label>
                    <p>{{ $favourite->description }}</p>
                    {!! $errors->first('favourite_id', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                </div>
                <hr style="margin:0">
                <div class="card-body text-danger">{{ __('favourite.delete_confirm') }}</div>
                <div class="card-footer">
                    <form method="POST" action="{{ route('favourites.destroy', $favourite) }}" accept-charset="UTF-8" onsubmit="return confirm(&quot;{{ __('app.delete_confirm') }}&quot;)" class="del-form float-right" style="display: inline;">
                        {{ csrf_field() }} {{ method_field('delete') }}
                        <input name="favourite_id" type="hidden" value="{{ $favourite->id }}">
                        <button type="submit" class="btn btn-danger">{{ __('app.delete_confirm_button') }}</button>
                    </form>
                    <a href="{{ route('favourites.edit', $favourite) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </div>
        @endcan
        @else
        <div class="card">
            <div class="card-header">{{ __('favourite.edit') }}</div>
            <form method="POST" action="{{ route('favourites.update', $favourite) }}" accept-charset="UTF-8">
                {{ csrf_field() }} {{ method_field('patch') }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="form-label">{{ __('favourite.name') }} <span class="form-required">*</span></label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $favourite->name) }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="description" class="form-label">{{ __('favourite.description') }}</label>
                        <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description', $favourite->description) }}</textarea>
                        {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('favourite.update') }}" class="btn btn-success">
                    <a href="{{ route('favourites.show', $favourite) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                    @can('delete', $favourite)
                        <a href="{{ route('favourites.edit', [$favourite, 'action' => 'delete']) }}" id="del-favourite-{{ $favourite->id }}" class="btn btn-danger float-right">{{ __('app.delete') }}</a>
                    @endcan
                </div>
            </form>
        </div>
    </div>
</div>
@endif
@endsection

resources/views/favourites/index.blade.php
@extends('layouts.app')

@section('title', __('favourite.list'))

@section('content')
<div class="mb-3">
    <div class="float-right">
        @can('create', new App\Favourite)
            <a href="{{ route('favourites.create') }}" class="btn btn-success">{{ __('favourite.create') }}</a>
        @endcan
    </div>
    <h1 class="page-title">{{ __('favourite.list') }} <small>{{ __('app.total') }} : {{ $favourites->total() }} {{ __('favourite.favourite') }}</small></h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <form method="GET" action="" accept-charset="UTF-8" class="form-inline">
                    <div class="form-group">
                        <label for="q" class="form-label">{{ __('favourite.search') }}</label>
                        <input placeholder="{{ __('favourite.search_text') }}" name="q" type="text" id="q" class="form-control mx-sm-2" value="{{ request('q') }}">
                    </div>
                    <input type="submit" value="{{ __('favourite.search') }}" class="btn btn-secondary">
                    <a href="{{ route('favourites.index') }}" class="btn btn-link">{{ __('app.reset') }}</a>
                </form>
            </div>
            <table class="table table-sm table-responsive-sm table-hover">
                <thead>
                    <tr>
                        <th class="text-center">{{ __('app.table_no') }}</th>
                        <th>{{ __('favourite.name') }}</th>
                        <th>{{ __('favourite.description') }}</th>
                        <th class="text-center">{{ __('app.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($favourites as $key => $favourite)
                    <tr>
                        <td class="text-center">{{ $favourites->firstItem() + $key }}</td>
                        <td>{!! $favourite->name_link !!}</td>
                        <td>{{ $favourite->description }}</td>
                        <td class="text-center">
                            @can('view', $favourite)
                                <a href="{{ route('favourites.show', $favourite) }}" id="show-favourite-{{ $favourite->id }}">{{ __('app.show') }}</a>
                            @endcan
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="card-body">{{ $favourites->appends(Request::except('page'))->render() }}</div>
        </div>
    </div>
</div>
@endsection

resources/views/favourites/show.blade.php
@extends('layouts.app')

@section('title', __('favourite.detail'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('favourite.detail') }}</div>
            <div class="card-body">
                <table class="table table-sm">
                    <tbody>
                        <tr><td>{{ __('favourite.name') }}</td><td>{{ $favourite->name }}</td></tr>
                        <tr><td>{{ __('favourite.description') }}</td><td>{{ $favourite->description }}</td></tr>
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                @can('update', $favourite)
                    <a href="{{ route('favourites.edit', $favourite) }}" id="edit-favourite-{{ $favourite->id }}" class="btn btn-warning">{{ __('favourite.edit') }}</a>
                @endcan
                <a href="{{ route('favourites.index') }}" class="btn btn-link">{{ __('favourite.back_to_index') }}</a>
            </div>
        </div>
    </div>
</div>
@endsection