routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});

/*
 * Subscribers Routes
 */
Route::resource('subscribers', 'SubscriberController');

/*
 * Aliases Routes
 */
Route::resource('aliases', 'AliasController');

/*
 * Reviews Routes
 */
Route::resource('reviews', 'ReviewController');

/*
 * Hoteliers Routes
 */
Route::resource('hoteliers', 'HotelierController');

/*
 * Hotels Routes
 */
Route::resource('hotels', 'HotelController');

/*
 * Photos Routes
 */
Route::resource('photos', 'PhotoController');

/*
 * Favourites Routes
 */
Route::resource('favourites', 'FavouriteController');

/*
 * SimilarHotels Routes
 */
Route::resource('similar_hotels', 'SimilarHotelController');

/*
 * HotelReviewRatings Routes
 */
Route::resource('hotel_review_ratings', 'HotelReviewRatingController');

/*
 * AnswerHotelQuestions Routes
 */
Route::resource('answer_hotel_questions', 'AnswerHotelQuestionController');

/*
 * SummaryStayTypes Routes
 */
Route::resource('summary_stay_types', 'SummaryStayTypeController');

/*
 * HotelServices Routes
 */
Route::resource('hotel_services', 'HotelServiceController');

/*
 * ReviewUsefulnesses Routes
 */
Route::resource('review_usefulnesses', 'ReviewUsefulnessController');

/*
 * HotelCategories Routes
 */
Route::resource('hotel_categories', 'HotelCategoryController');

/*
 * PriceRanges Routes
 */
Route::resource('price_ranges', 'PriceRangeController');

/*
 * Countries Routes
 */
Route::resource('countries', 'CountryController');

/*
 * VisitDates Routes
 */
Route::resource('visit_dates', 'VisitDateController');

/*
 * HotelQuestions Routes
 */
Route::resource('hotel_questions', 'HotelQuestionController');

/*
 * Services Routes
 */
Route::resource('services', 'ServiceController');

/*
 * HotelReviewTypes Routes
 */
Route::resource('hotel_review_types', 'HotelReviewTypeController');

/*
 * VisitTypes Routes
 */
Route::resource('visit_types', 'VisitTypeController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


/**
 * Multi-Authentication Routes
 */
Route::get('/login/subscriber', 'Auth\LoginController@showSubscriberLoginForm')->name('login_subscriber');
Route::get('/login/hotelier', 'Auth\LoginController@showHotelierLoginForm')->name('login_hotelier');
Route::get('/register/subscriber', 'Auth\RegisterController@showSubscriberRegisterForm')->name('register_subscriber');
Route::get('/register/hotelier', 'Auth\RegisterController@showHotelierRegisterForm')->name('register_hotelier');

Route::post('/login/subscriber', 'Auth\LoginController@subscriberLogin');
Route::post('/login/hotelier', 'Auth\LoginController@hotelierLogin');
Route::post('/register/subscriber', 'Auth\RegisterController@createSubscriber');
Route::post('/register/hotelier', 'Auth\RegisterController@createHotelier');

Route::view('/home', 'home')->middleware('auth');
Route::view('/dashboard', 'dashboard');

app/Alias.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Alias extends Model
{
    protected $fillable = ['hotel_id', 'description'];

    public function getNameLinkAttribute()
    {
        $title = __('app.show_detail_title', [
            'name' => $this->name, 'type' => __('alias.alias'),
        ]);
        $link = '<a href="'.route('aliases.show', $this).'"';
        $link .= ' title="'.$title.'">';
        $link .= $this->name;
        $link .= '</a>';

        return $link;
    }

    public function creator()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the Hotel associated with the Alias.
     */
    public function hotel()
    {
        return $this->belongsTo(Hotel::class);
    }
}

app/Http/Controllers/ReviewUsefulnessController.php
<?php

namespace App\Http\Controllers;

use App\ReviewUsefulness;
use Illuminate\Http\Request;

class ReviewUsefulnessController extends Controller
{
    /**
     * Display a listing of the reviewUsefulness.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $reviewUsefulnessQuery = ReviewUsefulness::query();
        $reviewUsefulnessQuery->where('name', 'like', '%'.request('q').'%');
        $reviewUsefulnesses = $reviewUsefulnessQuery->paginate(25);

        return view('review_usefulnesses.index', compact('reviewUsefulnesses'));
    }

    /**
     * Show the form for creating a new reviewUsefulness.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $this->authorize('create', new ReviewUsefulness);

        return view('review_usefulnesses.create');
    }

    /**
     * Store a newly created reviewUsefulness in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->authorize('create', new ReviewUsefulness);

        $newReviewUsefulness = $request->validate([
            'name'        => 'required|max:60',
            'description' => 'nullable|max:255',
        ]);
        $newReviewUsefulness['creator_id'] = auth()->id();

        $reviewUsefulness = ReviewUsefulness::create($newReviewUsefulness);

        return redirect()->route('review_usefulnesses.show', $reviewUsefulness);
    }

    /**
     * Display the specified reviewUsefulness.
     *
     * @param  \App\ReviewUsefulness  $reviewUsefulness
     * @return \Illuminate\View\View
     */
    public function show(ReviewUsefulness $reviewUsefulness)
    {
        return view('review_usefulnesses.show', compact('reviewUsefulness'));
    }

    /**
     * Show the form for editing the specified reviewUsefulness.
     *
     * @param  \App\ReviewUsefulness  $reviewUsefulness
     * @return \Illuminate\View\View
     */
    public function edit(ReviewUsefulness $reviewUsefulness)
    {
        $this->authorize('update', $reviewUsefulness);

        return view('review_usefulnesses.edit', compact('reviewUsefulness'));
    }

    /**
     * Update the specified reviewUsefulness in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ReviewUsefulness  $reviewUsefulness
     * @return \Illuminate\Routing\Redirector
     */
    public function update(Request $request, ReviewUsefulness $reviewUsefulness)
    {
        $this->authorize('update', $reviewUsefulness);

        $reviewUsefulnessData = $request->validate([
            'name'        => 'required|max:60',
            'description' => 'nullable|max:255',
        ]);
        $reviewUsefulness->update($reviewUsefulnessData);

        return redirect()->route('review_usefulnesses.show', $reviewUsefulness);
    }

    /**
     * Remove the specified reviewUsefulness from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ReviewUsefulness  $reviewUsefulness
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy(Request $request, ReviewUsefulness $reviewUsefulness)
    {
        $this->authorize('delete', $reviewUsefulness);

        $request->validate(['review_usefulness_id' => 'required']);

        if ($request->get('review_usefulness_id') == $reviewUsefulness->id && $reviewUsefulness->delete()) {
            return redirect()->route('review_usefulnesses.index');
        }

        return back();
    }
}

resources/views/review_usefulnesses/create.blade.php
@extends('layouts.app')

@section('title', __('review_usefulness.create'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('review_usefulness.create') }}</div>
            <form method="POST" action="{{ route('review_usefulnesses.store') }}" accept-charset="UTF-8">
                {{ csrf_field() }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="form-label">{{ __('review_usefulness.name') }} <span class="form-required">*</span></label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="description" class="form-label">{{ __('review_usefulness.description') }}</label>
                        <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description') }}</textarea>
                        {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('review_usefulness.create') }}" class="btn btn-success">
                    <a href="{{ route('review_usefulnesses.index') }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/review_usefulnesses/edit.blade.php
@extends('layouts.app')

@section('title', __('review_usefulness.edit'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        @if (request('action') == 'delete' && $reviewUsefulness)
        @can('delete', $reviewUsefulness)
            <div class="card">
                <div class="card-header">{{ __('review_usefulness.delete') }}</div>
                <div class="card-body">
                    <label class="form-label text-primary">{{ __('review_usefulness.name') }}</label>
                    <p>{{ $reviewUsefulness->name }}</p>
                    <label class="form-label text-primary">{{ __('review_usefulness.description') }}</label>
                    <p>{{ $reviewUsefulness->description }}</p>
                    {!! $errors->first('review_usefulness_id', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                </div>
                <hr style="margin:0">
                <div class="card-body text-danger">{{ __('review_usefulness.delete_confirm') }}</div>
                <div class="card-footer">
                    <form method="POST" action="{{ route('review_usefulnesses.destroy', $reviewUsefulness) }}" accept-charset="UTF-8" onsubmit="return confirm(&quot;{{ __('app.delete_confirm') }}&quot;)" class="del-form float-right" style="display: inline;">
                        {{ csrf_field() }} {{ method_field('delete') }}
                        <input name="review_usefulness_id" type="hidden" value="{{ $reviewUsefulness->id }}">
                        <button type="submit" class="btn btn-danger">{{ __('app.delete_confirm_button') }}</button>
                    </form>
                    <a href="{{ route('review_usefulnesses.edit', $reviewUsefulness) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </div>
        @endcan
        @else
        <div class="card">
            <div class="card-header">{{ __('review_usefulness.edit') }}</div>
            <form method="POST" action="{{ route('review_usefulnesses.update', $reviewUsefulness) }}" accept-charset="UTF-8">
                {{ csrf_field() }} {{ method_field('patch') }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="form-label">{{ __('review_usefulness.name') }} <span class="form-required">*</span></label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $reviewUsefulness->name) }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="description" class="form-label">{{ __('review_usefulness.description') }}</label>
                        <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description', $reviewUsefulness->description) }}</textarea>
                        {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('review_usefulness.update') }}" class="btn btn-success">
                    <a href="{{ route('review_usefulnesses.show', $reviewUsefulness) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                    @can('delete', $reviewUsefulness)
                        <a href="{{ route('review_usefulnesses.edit', [$reviewUsefulness, 'action' => 'delete']) }}" id="del-review_usefulness-{{ $reviewUsefulness->id }}" class="btn btn-danger float-right">{{ __('app.delete') }}</a>
                    @endcan
                </div>
            </form>
        </div>
    </div>
</div>
@endif
@endsection

resources/views/review_usefulnesses/index.blade.php
@extends('layouts.app')

@section('title', __('review_usefulness.list'))

@section('content')
<div class="mb-3">
    <div class="float-right">
        @can('create', new App\ReviewUsefulness)
            <a href="{{ route('review_usefulnesses.create') }}" class="btn btn-success">{{ __('review_usefulness.create') }}</a>
        @endcan
    </div>
    <h1 class="page-title">{{ __('review_usefulness.list') }} <small>{{ __('app.total') }} : {{ $reviewUsefulnesses->total() }} {{ __('review_usefulness.review_usefulness') }}</small></h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <form method="GET" action="" accept-charset="UTF-8" class="form-inline">
                    <div class="form-group">
                        <label for="q" class="form-label">{{ __('review_usefulness.search') }}</label>
                        <input placeholder="{{ __('review_usefulness.search_text') }}" name="q" type="text" id="q" class="form-control mx-sm-2" value="{{ request('q') }}">
                    </div>
                    <input type="submit" value="{{ __('review_usefulness.search') }}" class="btn btn-secondary">
                    <a href="{{ route('review_usefulnesses.index') }}" class="btn btn-link">{{ __('app.reset') }}</a>
                </form>
            </div>
            <table class="table table-sm table-responsive-sm table-hover">
                <thead>
                    <tr>
                        <th class="text-center">{{ __('app.table_no') }}</th>
                        <th>{{ __('review_usefulness.name') }}</th>
                        <th>{{ __('review_usefulness.description') }}</th>
                        <th class="text-center">{{ __('app.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($reviewUsefulnesses as $key => $reviewUsefulness)
                    <tr>
                        <td class="text-center">{{ $reviewUsefulnesses->firstItem() + $key }}</td>
                        <td>{!! $reviewUsefulness->name_link !!}</td>
                        <td>{{ $reviewUsefulness->description }}</td>
                        <td class="text-center">
                            @can('view', $reviewUsefulness)
                                <a href="{{ route('review_usefulnesses.show', $reviewUsefulness) }}" id="show-review_usefulness-{{ $reviewUsefulness->id }}">{{ __('app.show') }}</a>
                            @endcan
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="card-body">{{ $reviewUsefulnesses->appends(Request::except('page'))->render() }}</div>
        </div>
    </div>
</div>
@endsection

resources/views/review_usefulnesses/show.blade.php
@extends('layouts.app')

@section('title', __('review_usefulness.detail'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('review_usefulness.detail') }}</div>
            <div class="card-body">
                <table class="table table-sm">
                    <tbody>
                        <tr><td>{{ __('review_usefulness.name') }}</td><td>{{ $reviewUsefulness->name }}</td></tr>
                        <tr><td>{{ __('review_usefulness.description') }}</td><td>{{ $reviewUsefulness->description }}</td></tr>
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                @can('update', $reviewUsefulness)
                    <a href="{{ route('review_usefulnesses.edit', $reviewUsefulness) }}" id="edit-review_usefulness-{{ $reviewUsefulness->id }}" class="btn btn-warning">{{ __('review_usefulness.edit') }}</a>
                @endcan
                <a href="{{ route('review_usefulnesses.index') }}" class="btn btn-link">{{ __('review_usefulness.back_to_index') }}</a>
            </div>
        </div>
    </div>
</div>
@endsection