routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});

/*
 * Subscribers Routes
 */
Route::resource('subscribers', 'SubscriberController');

/*
 * Aliases Routes
 */
Route::resource('aliases', 'AliasController');

/*
 * Reviews Routes
 */
Route::resource('reviews', 'ReviewController');

/*
 * Hoteliers Routes
 */
Route::resource('hoteliers', 'HotelierController');

/*
 * Hotels Routes
 */
Route::resource('hotels', 'HotelController');

/*
 * Photos Routes
 */
Route::resource('photos', 'PhotoController');

/*
 * Favourites Routes
 */
Route::resource('favourites', 'FavouriteController');

/*
 * SimilarHotels Routes
 */
Route::resource('similar_hotels', 'SimilarHotelController');

/*
 * HotelReviewRatings Routes
 */
Route::resource('hotel_review_ratings', 'HotelReviewRatingController');

/*
 * AnswerHotelQuestions Routes
 */
Route::resource('answer_hotel_questions', 'AnswerHotelQuestionController');

/*
 * SummaryStayTypes Routes
 */
Route::resource('summary_stay_types', 'SummaryStayTypeController');

/*
 * HotelServices Routes
 */
Route::resource('hotel_services', 'HotelServiceController');

/*
 * ReviewUsefulnesses Routes
 */
Route::resource('review_usefulnesses', 'ReviewUsefulnessController');

/*
 * HotelCategories Routes
 */
Route::resource('hotel_categories', 'HotelCategoryController');

/*
 * PriceRanges Routes
 */
Route::resource('price_ranges', 'PriceRangeController');

/*
 * Countries Routes
 */
Route::resource('countries', 'CountryController');

/*
 * VisitDates Routes
 */
Route::resource('visit_dates', 'VisitDateController');

/*
 * HotelQuestions Routes
 */
Route::resource('hotel_questions', 'HotelQuestionController');

/*
 * Services Routes
 */
Route::resource('services', 'ServiceController');

/*
 * HotelReviewTypes Routes
 */
Route::resource('hotel_review_types', 'HotelReviewTypeController');

/*
 * VisitTypes Routes
 */
Route::resource('visit_types', 'VisitTypeController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


/**
 * Multi-Authentication Routes
 */
Route::get('/login/subscriber', 'Auth\LoginController@showSubscriberLoginForm')->name('login_subscriber');
Route::get('/login/hotelier', 'Auth\LoginController@showHotelierLoginForm')->name('login_hotelier');
Route::get('/register/subscriber', 'Auth\RegisterController@showSubscriberRegisterForm')->name('register_subscriber');
Route::get('/register/hotelier', 'Auth\RegisterController@showHotelierRegisterForm')->name('register_hotelier');

Route::post('/login/subscriber', 'Auth\LoginController@subscriberLogin');
Route::post('/login/hotelier', 'Auth\LoginController@hotelierLogin');
Route::post('/register/subscriber', 'Auth\RegisterController@createSubscriber');
Route::post('/register/hotelier', 'Auth\RegisterController@createHotelier');

Route::view('/home', 'home')->middleware('auth');
Route::view('/dashboard', 'dashboard');

app/HotelService.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class HotelService extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'hotel_service';
    
    protected $fillable = ['name', 'description', 'creator_id'];

    public function getNameLinkAttribute()
    {
        $title = __('app.show_detail_title', [
            'name' => $this->name, 'type' => __('hotel_service.hotel_service'),
        ]);
        $link = '<a href="'.route('hotel_services.show', $this).'"';
        $link .= ' title="'.$title.'">';
        $link .= $this->name;
        $link .= '</a>';

        return $link;
    }

    public function creator()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/HotelServiceController.php
<?php

namespace App\Http\Controllers;

use App\HotelService;
use Illuminate\Http\Request;

class HotelServiceController extends Controller
{
    /**
     * Display a listing of the hotelService.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $hotelServiceQuery = HotelService::query();
        $hotelServiceQuery->where('name', 'like', '%'.request('q').'%');
        $hotelServices = $hotelServiceQuery->paginate(25);

        return view('hotel_services.index', compact('hotelServices'));
    }

    /**
     * Show the form for creating a new hotelService.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $this->authorize('create', new HotelService);

        return view('hotel_services.create');
    }

    /**
     * Store a newly created hotelService in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->authorize('create', new HotelService);

        $newHotelService = $request->validate([
            'name'        => 'required|max:60',
            'description' => 'nullable|max:255',
        ]);
        $newHotelService['creator_id'] = auth()->id();

        $hotelService = HotelService::create($newHotelService);

        return redirect()->route('hotel_services.show', $hotelService);
    }

    /**
     * Display the specified hotelService.
     *
     * @param  \App\HotelService  $hotelService
     * @return \Illuminate\View\View
     */
    public function show(HotelService $hotelService)
    {
        return view('hotel_services.show', compact('hotelService'));
    }

    /**
     * Show the form for editing the specified hotelService.
     *
     * @param  \App\HotelService  $hotelService
     * @return \Illuminate\View\View
     */
    public function edit(HotelService $hotelService)
    {
        $this->authorize('update', $hotelService);

        return view('hotel_services.edit', compact('hotelService'));
    }

    /**
     * Update the specified hotelService in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\HotelService  $hotelService
     * @return \Illuminate\Routing\Redirector
     */
    public function update(Request $request, HotelService $hotelService)
    {
        $this->authorize('update', $hotelService);

        $hotelServiceData = $request->validate([
            'name'        => 'required|max:60',
            'description' => 'nullable|max:255',
        ]);
        $hotelService->update($hotelServiceData);

        return redirect()->route('hotel_services.show', $hotelService);
    }

    /**
     * Remove the specified hotelService from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\HotelService  $hotelService
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy(Request $request, HotelService $hotelService)
    {
        $this->authorize('delete', $hotelService);

        $request->validate(['hotel_service_id' => 'required']);

        if ($request->get('hotel_service_id') == $hotelService->id && $hotelService->delete()) {
            return redirect()->route('hotel_services.index');
        }

        return back();
    }
}

resources/views/hotel_services/create.blade.php
@extends('layouts.app')

@section('title', __('hotel_service.create'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('hotel_service.create') }}</div>
            <form method="POST" action="{{ route('hotel_services.store') }}" accept-charset="UTF-8">
                {{ csrf_field() }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="form-label">{{ __('hotel_service.name') }} <span class="form-required">*</span></label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="description" class="form-label">{{ __('hotel_service.description') }}</label>
                        <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description') }}</textarea>
                        {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('hotel_service.create') }}" class="btn btn-success">
                    <a href="{{ route('hotel_services.index') }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/hotel_services/edit.blade.php
@extends('layouts.app')

@section('title', __('hotel_service.edit'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        @if (request('action') == 'delete' && $hotelService)
        @can('delete', $hotelService)
            <div class="card">
                <div class="card-header">{{ __('hotel_service.delete') }}</div>
                <div class="card-body">
                    <label class="form-label text-primary">{{ __('hotel_service.name') }}</label>
                    <p>{{ $hotelService->name }}</p>
                    <label class="form-label text-primary">{{ __('hotel_service.description') }}</label>
                    <p>{{ $hotelService->description }}</p>
                    {!! $errors->first('hotel_service_id', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                </div>
                <hr style="margin:0">
                <div class="card-body text-danger">{{ __('hotel_service.delete_confirm') }}</div>
                <div class="card-footer">
                    <form method="POST" action="{{ route('hotel_services.destroy', $hotelService) }}" accept-charset="UTF-8" onsubmit="return confirm(&quot;{{ __('app.delete_confirm') }}&quot;)" class="del-form float-right" style="display: inline;">
                        {{ csrf_field() }} {{ method_field('delete') }}
                        <input name="hotel_service_id" type="hidden" value="{{ $hotelService->id }}">
                        <button type="submit" class="btn btn-danger">{{ __('app.delete_confirm_button') }}</button>
                    </form>
                    <a href="{{ route('hotel_services.edit', $hotelService) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </div>
        @endcan
        @else
        <div class="card">
            <div class="card-header">{{ __('hotel_service.edit') }}</div>
            <form method="POST" action="{{ route('hotel_services.update', $hotelService) }}" accept-charset="UTF-8">
                {{ csrf_field() }} {{ method_field('patch') }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="form-label">{{ __('hotel_service.name') }} <span class="form-required">*</span></label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $hotelService->name) }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="description" class="form-label">{{ __('hotel_service.description') }}</label>
                        <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description', $hotelService->description) }}</textarea>
                        {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('hotel_service.update') }}" class="btn btn-success">
                    <a href="{{ route('hotel_services.show', $hotelService) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                    @can('delete', $hotelService)
                        <a href="{{ route('hotel_services.edit', [$hotelService, 'action' => 'delete']) }}" id="del-hotel_service-{{ $hotelService->id }}" class="btn btn-danger float-right">{{ __('app.delete') }}</a>
                    @endcan
                </div>
            </form>
        </div>
    </div>
</div>
@endif
@endsection

resources/views/hotel_services/index.blade.php
@extends('layouts.app')

@section('title', __('hotel_service.list'))

@section('content')
<div class="mb-3">
    <div class="float-right">
        @can('create', new App\HotelService)
            <a href="{{ route('hotel_services.create') }}" class="btn btn-success">{{ __('hotel_service.create') }}</a>
        @endcan
    </div>
    <h1 class="page-title">{{ __('hotel_service.list') }} <small>{{ __('app.total') }} : {{ $hotelServices->total() }} {{ __('hotel_service.hotel_service') }}</small></h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <form method="GET" action="" accept-charset="UTF-8" class="form-inline">
                    <div class="form-group">
                        <label for="q" class="form-label">{{ __('hotel_service.search') }}</label>
                        <input placeholder="{{ __('hotel_service.search_text') }}" name="q" type="text" id="q" class="form-control mx-sm-2" value="{{ request('q') }}">
                    </div>
                    <input type="submit" value="{{ __('hotel_service.search') }}" class="btn btn-secondary">
                    <a href="{{ route('hotel_services.index') }}" class="btn btn-link">{{ __('app.reset') }}</a>
                </form>
            </div>
            <table class="table table-sm table-responsive-sm table-hover">
                <thead>
                    <tr>
                        <th class="text-center">{{ __('app.table_no') }}</th>
                        <th>{{ __('hotel_service.name') }}</th>
                        <th>{{ __('hotel_service.description') }}</th>
                        <th class="text-center">{{ __('app.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($hotelServices as $key => $hotelService)
                    <tr>
                        <td class="text-center">{{ $hotelServices->firstItem() + $key }}</td>
                        <td>{!! $hotelService->name_link !!}</td>
                        <td>{{ $hotelService->description }}</td>
                        <td class="text-center">
                            @can('view', $hotelService)
                                <a href="{{ route('hotel_services.show', $hotelService) }}" id="show-hotel_service-{{ $hotelService->id }}">{{ __('app.show') }}</a>
                            @endcan
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="card-body">{{ $hotelServices->appends(Request::except('page'))->render() }}</div>
        </div>
    </div>
</div>
@endsection

resources/views/hotel_services/show.blade.php
@extends('layouts.app')

@section('title', __('hotel_service.detail'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('hotel_service.detail') }}</div>
            <div class="card-body">
                <table class="table table-sm">
                    <tbody>
                        <tr><td>{{ __('hotel_service.name') }}</td><td>{{ $hotelService->name }}</td></tr>
                        <tr><td>{{ __('hotel_service.description') }}</td><td>{{ $hotelService->description }}</td></tr>
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                @can('update', $hotelService)
                    <a href="{{ route('hotel_services.edit', $hotelService) }}" id="edit-hotel_service-{{ $hotelService->id }}" class="btn btn-warning">{{ __('hotel_service.edit') }}</a>
                @endcan
                <a href="{{ route('hotel_services.index') }}" class="btn btn-link">{{ __('hotel_service.back_to_index') }}</a>
            </div>
        </div>
    </div>
</div>
@endsection